name: Linux.do 自动点赞

on:
  schedule:
    # 上海时间中午12点 = UTC时间早上4点 (UTC+8)
    - cron: '0 4 * * *'
  
  # 允许手动触发
  workflow_dispatch:

jobs:
  auto-like:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    
    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install curl-cffi
    
    - name: 运行自动点赞脚本
      env:
        LINUX_DO_EMAIL: ${{ secrets.LINUX_DO_EMAIL }}
        LINUX_DO_PASSWORD: ${{ secrets.LINUX_DO_PASSWORD }}
        CF_CLEARANCE: ${{ secrets.CF_CLEARANCE }}
        ENABLE_LIKE: ${{ vars.ENABLE_LIKE || 'true' }}
        LIKE_COUNT: ${{ vars.LIKE_COUNT || '5' }}
        BROWSE_COUNT: ${{ vars.BROWSE_COUNT || '' }}
      run: |
        echo "开始执行 Linux.do 自动点赞任务..."
        echo "当前时间 (UTC): $(date -u)"
        echo "当前时间 (上海): $(TZ='Asia/Shanghai' date)"
        python main.py
    
    - name: 上传运行日志
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: auto-like-logs-${{ github.run_number }}
        path: |
          *.log
        retention-days: 7
